# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.7
   install:
      - method: pip
        path: .
        extra_requirements:
           - sphinx_gallery