name: CI

on: [push]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Install package
        run: |
          pip install -e .         

      - name: Run tests
        run: pytest
        
  package-checks:
    name: package checks

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install check dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel check-manifest isort twine
    - name: Check package import order
      run: |
        isort --verbose --check-only --diff src tests setup.py
    - name: Check package contents
      run: |
        python setup.py sdist check --strict --metadata
        check-manifest
        twine check dist/*
